repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: update-version
        name: Confirm that the version in pyproject matches the source.
        entry: python scripts/update_version.py
        language: system
        files: '(\.py$|pyproject.toml)'
      - id: check-unstaged
        name: Check for unstaged changes.
        entry: scripts/check_unstaged.sh
        language: script
        files: '.*'
